// Mock attachment download helper.
//
// Real files don't exist in this mock build — message attachments are
// seed-only metadata with no upload backend. To make Download / Open buttons
// behave like a real action, we synthesize a placeholder text blob carrying
// the file's metadata and trigger a browser download for it.
//
// The action is visible (a real file lands in the user's Downloads folder)
// and the workflow completes without requiring a backend or any new routes.

import type { Attachment } from "@/data/messages";
import { attachmentLabel, formatBytes } from "@/data/messages";

function placeholderBody(attachment: Attachment): string {
  return [
    "Capital Circle — attachment placeholder",
    "----------------------------------------",
    `Name      : ${attachment.name}`,
    `Type      : ${attachmentLabel(attachment.type)}`,
    `Size      : ${formatBytes(attachment.sizeBytes)}`,
    `ID        : ${attachment.id}`,
    "",
    "The real document is not stored in this mock build. This placeholder",
    "is generated by the client when you tap Download or Open so the action",
    "completes end-to-end without a backend.",
    "",
  ].join("\n");
}

/**
 * Triggers a browser download for a synthesized text placeholder of an
 * attachment. Returns true if the click was dispatched; false if the
 * environment isn't a browser (e.g. SSR).
 */
export function downloadAttachmentPlaceholder(attachment: Attachment): boolean {
  if (typeof window === "undefined" || typeof document === "undefined") {
    return false;
  }
  const body = placeholderBody(attachment);
  const blob = new Blob([body], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  // Append a `.txt` suffix when the original name doesn't carry an extension
  // we can write to disk.
  const safeName = /\.[a-z0-9]+$/i.test(attachment.name)
    ? `${attachment.name}.txt`
    : `${attachment.name || "attachment"}.txt`;
  const a = document.createElement("a");
  a.href = url;
  a.download = safeName;
  a.rel = "noopener";
  // Some browsers require the anchor to be in the DOM before .click().
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Defer revoke so the browser has time to start the download.
  window.setTimeout(() => URL.revokeObjectURL(url), 250);
  return true;
}
