// Mock data-room document open / download helper.
//
// Documents in the seed data carry no real file URLs. To make the View /
// Download buttons in the data room produce a visible action (the audit
// flagged them as activity-log shims), we synthesize a placeholder text
// blob from the document's metadata and trigger a real browser action
// for it — opening in a new tab for "view", downloading for "download".

import type { DataRoomDocument } from "@/data/documents";

function placeholderBody(doc: DataRoomDocument): string {
  return [
    "Capital Circle — document placeholder",
    "-------------------------------------",
    `Name      : ${doc.name}`,
    `Category  : ${doc.category}`,
    `Type      : ${doc.fileType.toUpperCase()}`,
    `Visibility: ${doc.visibility}`,
    `Size      : ${doc.sizeBytes} bytes`,
    doc.pages != null ? `Pages     : ${doc.pages}` : null,
    `Listing   : ${doc.listingId}`,
    "",
    "The real document is not stored in this mock build. This placeholder",
    "is generated by the client when you tap View or Download so the action",
    "produces a real artifact without a backend.",
    "",
    doc.description ?? "",
  ]
    .filter(Boolean)
    .join("\n");
}

function buildBlobUrl(doc: DataRoomDocument): {
  url: string;
  fileName: string;
} | null {
  if (typeof window === "undefined" || typeof document === "undefined") {
    return null;
  }
  const blob = new Blob([placeholderBody(doc)], {
    type: "text/plain;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const fileName = /\.[a-z0-9]+$/i.test(doc.name)
    ? `${doc.name}.txt`
    : `${doc.name || "document"}.txt`;
  return { url, fileName };
}

/** Open the placeholder in a new browser tab — visible "view" action. */
export function openDocumentPlaceholder(doc: DataRoomDocument): boolean {
  const built = buildBlobUrl(doc);
  if (!built) return false;
  // Use a hidden anchor with target="_blank" + rel="noopener" so the action
  // works in standalone PWAs / strict popup blockers.
  const a = window.document.createElement("a");
  a.href = built.url;
  a.target = "_blank";
  a.rel = "noopener";
  window.document.body.appendChild(a);
  a.click();
  window.document.body.removeChild(a);
  // Revoke after a delay so the new tab has time to load.
  window.setTimeout(() => URL.revokeObjectURL(built.url), 30_000);
  return true;
}

/** Trigger a real download of the placeholder — visible "download" action. */
export function downloadDocumentPlaceholder(doc: DataRoomDocument): boolean {
  const built = buildBlobUrl(doc);
  if (!built) return false;
  const a = window.document.createElement("a");
  a.href = built.url;
  a.download = built.fileName;
  a.rel = "noopener";
  window.document.body.appendChild(a);
  a.click();
  window.document.body.removeChild(a);
  window.setTimeout(() => URL.revokeObjectURL(built.url), 250);
  return true;
}
